# Use uma imagem base do Python
FROM python:3.12-slim

# Defina o diretório de trabalho dentro do container
WORKDIR /app

# Copie o arquivo requirements.txt para o container
COPY requirements.txt .

# Instale as dependências a partir do requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copie o código da aplicação para o container
COPY . /app

EXPOSE 65433

# Defina o comando que será executado quando o container iniciar
CMD ["python3", "server.py"]
