#dockerfile.client

#imagem python usada
FROM python:3.12-slim

#defindo o diretório de trabalho
WORKDIR /app

#copiando todos os arquivos para o diretório de trabalho
COPY . /app

#comando para iniciar o cliente
CMD ["python3", "client.py"]
